### ISSUE TITLE
zad24 błąd

### ISSUE THREAD

**Issue by Vex0on** [pjastr/POcw1isi3#1]
```py
if n % 2 == 0:
    med = (sortlist[n // 2] + sortlist[n // 2 + 1]) / 2
else:
    med = sortlist[((n + 1) // 2)]
```

Warunki są nieprawidłowe. Przykład dla else poniżej

Załóżmy przypadek listy:
```py
list1 = [1, 2, 3, 4, 5]
```
Długość tej listy to 5, więc modulo zwraca 1
W takim razie korzystamy z warunku `else`
Linijka `med = sortlist[((n + 1) // 2)]` zwróci (5 + 1) // 2 czyli 3, a `list1[3]` to 4, ponieważ musimy uwzględnić indeks od 0

Tak samo działa warunek `if`, też trzeba przesunąć indeks o jeden do tyłu, ponieważ zaczynamy od 0, a nie 1

Poprawione proponowane rozwiązanie:
```py
import random
import statistics

random.seed(162681)
randomList = [random.randrange(1, 101) for i in range(200)]


def median(tab):
    sortlist = tab.copy()
    sortlist.sort()
    lng = len(sortlist)
    if lng % 2 == 0:
        median = (sortlist[(lng - 1) // 2] + sortlist[lng // 2]) / 2
    else:
        median = sortlist[lng // 2]

    return median


print(f'Wbudowana mediana: {statistics.median(randomList)}')
print(f'Moja mediana: {median(randomList)}')
```

**Comment by pjastr** [comment]
Dziękuję za zwrócenie uwagi.
